version: "3.9" # optional since v1.27.0
services:
  mysql-db:
    # platform: linux/amd64
    image: mysql:8
    container_name: mysql_db
    ports:
      - 3320:3306
    restart: always
    environment:
      # MYSQL_DATABASE: allmotors_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - project-db:/var/lib/mysql
  web:
    links:
      - mysql-db
    depends_on:
      - mysql-db
    container_name: next-js
    ports:
      - 80:3000
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: sarb123/allmotors:1.0
    env_file:
      - .env

volumes:
  project-db:
