export const buying_status = ["available", "reserved", "sold"];
export const make = [
  "AUDI",
  "BMW",
  "BMW Alpina",
  "Bristol",
  "Bugatti",
  "Chevrolet",
  "Citroen",
  "Dacia",
  "Fiat",
  "Farari",
  "Ford",
  "Jeep",
  "Jaguar",
  "Honda",
  "Hyundai",
  "Kia",
  "Land rover",
  "Lexus",
  "Lotus",
  "Mazda",
  "Mercedes-Benz",
  "Mercedes-AMG",
  "Mini",
  "Mitsubishi",
  "mahindra",
  "MG",
  "Nissan",
  "Peugeot",
  "Porsche",
  "Renault",
  "Range Rover",
  "Seat",
  "Skoda",
  "Suzuki",
  "Toyota",
  "Vauxhall",
  "Volkswagen",
  "Volvo",
];
export const color = [
  "white",
  "black",
  "green",
  "red",
  "orange",
  "gray",
  "silver",
  "blue",
  "yellow",
  "brown",
  "gold",
  "beige",
  "purple",
];

export const transmission = ["manual", "automatic", "semi auto"];
export const body = [
  "Convertible",
  "Coupe",
  "4x4",
  "mpv",
  "Pick Up",
  "Estate",
  "Hatchback",
  "Saloon",
];
export const vehicles = ["Car", "Van"];
export const fuel = [
  "gasoline",
  "Ethanol",
  "Flex",
  "diesel",
  "petrol",
  "hybrid",
  "electric",
];
export const doors = ["2", "3", "4", "5"];
export const steering = ["hydrolic", "mecanic", "electic"];
